### ISSUE TITLE
error: set: unknown line property sisotool

### ISSUE THREAD

**Issue by Alexander-Wilms** [EriveltonGualter/octave-control#1]
I saw that this issue was already reported [here](http://lists.gnu.org/archive/html/octave-maintainers/2018-06/msg00103.html), but I'm also able to reproduce this on Linux with Octave 4.4.0.

I used this package: https://github.com/flathub/org.octave.Octave/

**Comment by EriveltonGualter** [comment]
Hi Alexander, 

Would you mind giving it another try to install this package.

I believe I fixed all the issues.

Here is a small documentation: https://eriveltongualter.github.io/GSoC2018/pages/documentation.html
and a video: https://www.youtube.com/watch?v=w7VHZT6MNEI

**Comment by Alexander-Wilms** [comment]
Hi Erivelton,

I can confirm it's now fixed. Thanks!
