### ISSUE TITLE
Absolute icon paths

### ISSUE THREAD

**Issue by Alexander-Wilms** [EriveltonGualter/octave-control#3]
Hi,

I had to change the absolute paths to the root locus editor icons to relative ones to make them show up: https://github.com/EriveltonGualter/octave-control/blob/master/TARGET/control-3.1.0_gsoc/inst/GUI_sisotool.m#L503

Also, I'm not sure what the main script is that's being worked on: https://github.com/EriveltonGualter/octave-control/blob/master/inst/GUI_sisotool.m or https://github.com/EriveltonGualter/octave-control/blob/master/TARGET/control-3.1.0_gsoc/inst/GUI_sisotool.m?

**Comment by EriveltonGualter** [comment]
Thank you Alexander.

I already fixed it and seems it is working now.
